// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: TCPPacket.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct TCPPacket {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var sourceAddress: String = String()

  var destinationAddress: String = String()

  var sourcePort: UInt32 = 0

  var destinationPort: UInt32 = 0

  var payload: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

#if swift(>=5.5) && canImport(_Concurrency)
extension TCPPacket: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension TCPPacket: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "TCPPacket"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "sourceAddress"),
    2: .same(proto: "destinationAddress"),
    3: .same(proto: "sourcePort"),
    4: .same(proto: "destinationPort"),
    5: .same(proto: "payload"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.sourceAddress) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.destinationAddress) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.sourcePort) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.destinationPort) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.payload) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.sourceAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.sourceAddress, fieldNumber: 1)
    }
    if !self.destinationAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.destinationAddress, fieldNumber: 2)
    }
    if self.sourcePort != 0 {
      try visitor.visitSingularUInt32Field(value: self.sourcePort, fieldNumber: 3)
    }
    if self.destinationPort != 0 {
      try visitor.visitSingularUInt32Field(value: self.destinationPort, fieldNumber: 4)
    }
    if !self.payload.isEmpty {
      try visitor.visitSingularBytesField(value: self.payload, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: TCPPacket, rhs: TCPPacket) -> Bool {
    if lhs.sourceAddress != rhs.sourceAddress {return false}
    if lhs.destinationAddress != rhs.destinationAddress {return false}
    if lhs.sourcePort != rhs.sourcePort {return false}
    if lhs.destinationPort != rhs.destinationPort {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
